### ISSUE TITLE
Imcompatibility ACER NITRO V15 RTX 3050, Using Pop!_Os, Kernel 6.12.10-76061203-generic

### ISSUE THREAD

**Issue by Wesley00s** [PXDiv/Div-Acer-Manager-Max#32]
==========================================
       DAMX Suite Installer v0.7.10        
    Acer Laptop WMI Controls for Linux  
==========================================

Starting complete installation...
Checking for legacy installations...
No legacy installations found.

Installing Linuwu-Sense drivers...
make -C /lib/modules/6.12.10-76061203-generic/build M=/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense clean
make[1]: Entering directory '/usr/src/linux-headers-6.12.10-76061203-generic'
make[1]: Leaving directory '/usr/src/linux-headers-6.12.10-76061203-generic'
make -C /lib/modules/6.12.10-76061203-generic/build M=/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense modules
make[1]: Entering directory '/usr/src/linux-headers-6.12.10-76061203-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  CC [M]  /home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.o
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2245:22: error: variable ‘acer_predator_v4_platform_profile_ops’ has initializer but incomplete type
 2245 |  static const struct platform_profile_ops acer_predator_v4_platform_profile_ops = {
      |                      ^~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2246:7: error: ‘const struct platform_profile_ops’ has no member named ‘probe’
 2246 |      .probe = acer_predator_v4_platform_profile_probe,
      |       ^~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2246:15: warning: excess elements in struct initializer
 2246 |      .probe = acer_predator_v4_platform_profile_probe,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2246:15: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2247:7: error: ‘const struct platform_profile_ops’ has no member named ‘profile_get’
 2247 |      .profile_get = acer_predator_v4_platform_profile_get,
      |       ^~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2247:21: warning: excess elements in struct initializer
 2247 |      .profile_get = acer_predator_v4_platform_profile_get,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2247:21: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2248:7: error: ‘const struct platform_profile_ops’ has no member named ‘profile_set’
 2248 |      .profile_set = acer_predator_v4_platform_profile_set,
      |       ^~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2248:21: warning: excess elements in struct initializer
 2248 |      .profile_set = acer_predator_v4_platform_profile_set,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2248:21: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c: In function ‘acer_platform_profile_setup’:
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2254:36: error: implicit declaration of function ‘devm_platform_profile_register’; did you mean ‘platform_profile_register’? [-Werror=implicit-function-declaration]
 2254 |          platform_profile_device = devm_platform_profile_register(
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                    platform_profile_register
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2254:34: warning: assignment to ‘struct device *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2254 |          platform_profile_device = devm_platform_profile_register(
      |                                  ^
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c: In function ‘acer_thermal_profile_change’:
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2339:10: error: too many arguments to function ‘platform_profile_notify’
 2339 |          platform_profile_notify(platform_profile_device);
      |          ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:22:
./include/linux/platform_profile.h:40:6: note: declared here
   40 | void platform_profile_notify(void);
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c: At top level:
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2245:43: error: storage size of ‘acer_predator_v4_platform_profile_ops’ isn’t known
 2245 |  static const struct platform_profile_ops acer_predator_v4_platform_profile_ops = {
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:229: /home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.12.10-76061203-generic/Makefile:1943: /home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.12.10-76061203-generic'
make: *** [Makefile:12: all] Error 2
make -C /lib/modules/6.12.10-76061203-generic/build M=/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense modules
make[1]: Entering directory '/usr/src/linux-headers-6.12.10-76061203-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  CC [M]  /home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.o
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2245:22: error: variable ‘acer_predator_v4_platform_profile_ops’ has initializer but incomplete type
 2245 |  static const struct platform_profile_ops acer_predator_v4_platform_profile_ops = {
      |                      ^~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2246:7: error: ‘const struct platform_profile_ops’ has no member named ‘probe’
 2246 |      .probe = acer_predator_v4_platform_profile_probe,
      |       ^~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2246:15: warning: excess elements in struct initializer
 2246 |      .probe = acer_predator_v4_platform_profile_probe,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2246:15: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2247:7: error: ‘const struct platform_profile_ops’ has no member named ‘profile_get’
 2247 |      .profile_get = acer_predator_v4_platform_profile_get,
      |       ^~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2247:21: warning: excess elements in struct initializer
 2247 |      .profile_get = acer_predator_v4_platform_profile_get,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2247:21: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2248:7: error: ‘const struct platform_profile_ops’ has no member named ‘profile_set’
 2248 |      .profile_set = acer_predator_v4_platform_profile_set,
      |       ^~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2248:21: warning: excess elements in struct initializer
 2248 |      .profile_set = acer_predator_v4_platform_profile_set,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2248:21: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c: In function ‘acer_platform_profile_setup’:
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2254:36: error: implicit declaration of function ‘devm_platform_profile_register’; did you mean ‘platform_profile_register’? [-Werror=implicit-function-declaration]
 2254 |          platform_profile_device = devm_platform_profile_register(
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                    platform_profile_register
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2254:34: warning: assignment to ‘struct device *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2254 |          platform_profile_device = devm_platform_profile_register(
      |                                  ^
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c: In function ‘acer_thermal_profile_change’:
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2339:10: error: too many arguments to function ‘platform_profile_notify’
 2339 |          platform_profile_notify(platform_profile_device);
      |          ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:22:
./include/linux/platform_profile.h:40:6: note: declared here
   40 | void platform_profile_notify(void);
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c: At top level:
/home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.c:2245:43: error: storage size of ‘acer_predator_v4_platform_profile_ops’ isn’t known
 2245 |  static const struct platform_profile_ops acer_predator_v4_platform_profile_ops = {
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:229: /home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense/src/linuwu_sense.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.12.10-76061203-generic/Makefile:1943: /home/wesley/Downloads/DAMX-0.7.10/Linuwu-Sense] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.12.10-76061203-generic'
make: *** [Makefile:12: all] Error 2
Error: Failed to install Linuwu-Sense drivers
Press any key to continue...
Installing DAMX-Daemon...
Created symlink /etc/systemd/system/multi-user.target.wants/damx-daemon.service → /etc/systemd/system/damx-daemon.service.
DAMX-Daemon installed and service started successfully!
Installing DAMX-GUI...
DAMX-GUI installed successfully!
Some components failed to install. Please check the errors above.
Press any key to continue...

**Comment by PXDiv** [comment]
It looks like the driver is failing to build because of changes in the Pop os Linux 6.12 kernel. Specifically, the platform_profile_ops struct and some related functions (probe, profile_get, devm_platform_profile_register, etc.) have either been removed or changed in newer kernel versions.

Tho the driver works with written for an earlier kernel 6.13 and 6.14.

Options for Now:
- Upgrade to ubuntu 25 or kubuntu 25 (the app is officially supported for that distro)
- Put the same issue in the Linuwu sense drivers github. (link in readme) as they are the actual developers of the drivers
