### ISSUE TITLE
GPU Fan speed issues

### ISSUE THREAD

**Issue by AntonioRocha17** [PXDiv/Div-Acer-Manager-Max#247]
Using Operating System: CachyOS Linux 
KDE Plasma Version: 6.7.4
KDE Frameworks Version: 6.29.0
Qt Version: 6.11.2
Kernel Version: 7.2.0-rc7-1-cachyos-rc (64-bit)
Graphics Platform: Wayland
Processors: 12 × 13th Gen Intel® Core™ i5-13420H
Memory: 32 GiB of RAM (31,0 GiB usable)
Graphics Processor 1: NVIDIA GeForce RTX 3050 6GB Laptop GPU/PCIe/SSE2
Graphics Processor 2: NVIDIA GeForce RTX 3050 6GB Laptop GPU/PCIe/SSE2
Manufacturer: Acer
Product Name: Nitro ANV15-51
System Version: V1.60

Just installed the latest versions and these are my problems:

CPU fan speed do work but it doesn't change GPU fan speed, not with auto nor manual settings.

And whenever I switch profiles (balanced to performance) it goes to manual fan curve and doesn't allow me to switch back to auto unless I set quiet mode then go back to either balanced or performance

**Comment by AntonioRocha17** [comment]
I got it working with the help of LLM (Since I'm not a developer) and here are the changes I made:

Overview of Issues

When attempting to set the GPU fan to 100% via the DAMX GUI, the fan would get stuck at exactly 10%. Digging into the logs and the build process revealed a chain reaction of three distinct bugs preventing the driver from updating and functioning correctly on modern kernels.
1. Fatal Compilation Errors on Kernel 7.2.0+

The linuwu_sense.c file fails to compile on Linux 7.2+ due to two upstream kernel changes:

    Missing va_list definitions: Kernel 7.2 reorganized header inclusions to speed up build times. It no longer automatically includes <linux/stdarg.h>, resulting in cascading unknown type name 'va_list' errors from <linux/sprintf.h>.

    strncpy completely removed: The kernel community has deprecated and fully removed strncpy from the string API for security reasons. The compiler throws a fatal error: call to undeclared library function 'strncpy'.

2. Silent Installer Failure (Masking the Bug)

Because strncpy caused a fatal compile error, the .ko module was never generated. However, the install.sh / Makefile sequence does not catch this failure. It silently proceeds, meaning modprobe continues to load the old, stale module left in /lib/modules/$(uname -r)/.... This masks the compile error from the user and preserves older bugs in the system memory.
3. String Truncation Logic Bug (The "10%" GPU Fan Bug)

In the older compiled versions of the driver, the _store functions used strncpy in a way that truncated the payload.
C

size_t len = min(count, sizeof(input) - 1);
strncpy(input, buf, len);

By passing len as the total buffer size, it forced the last character of the payload to be dropped to make room for a null terminator. A GUI payload of "100,100" was successfully received by the kernel but truncated to "100,10", applying 10% to the GPU fan.
The Implemented Fixes (Code Patch)

To successfully compile and fix the string parsing, the following changes were made to src/linuwu_sense.c:

A. Added missing header (around line 30):
C

#include <linux/stdarg.h>
#include <linux/kernel.h>

B. Replaced strncpy with strscpy in the _store functions:
The string parsing logic in predator_fan_speed_store, four_zoned_rgb_kb_store, and per_zoned_rgb_kb_store was refactored to use the modern strscpy API, passing the absolute buffer size to guarantee null-termination without truncating the actual payload.

Example fix applied to predator_fan_speed_store:
C

    char input[16];
    char *token;
    char *input_ptr = input;

    // Use strscpy with absolute buffer size
    strscpy(input, buf, sizeof(input));

    // Strip trailing newline safely
    size_t len = strlen(input);
    if (len > 0 && input[len - 1] == '\n') {
        input[len - 1] = '\0';
    }

    token = strsep(&input_ptr, ",");
    // ... [proceed with kstrtoint]

(This exact strscpy and newline-stripping structure was mirrored to four_zoned_rgb_kb_store and per_zoned_rgb_kb_store, replacing all instances of strncpy).


I won't be posting the LLM suggestions since I didn't do the changes myself and I'm not bold enough to suggest something to the project lmao
I rather just provide information and let you be the judge of what to do and what not to do!
(been using damx since I started using linux back in july 2025)

**Comment by CreatorOfBiontium** [comment]
Why closed as completed?
Also ref #244
